apiVersion: v1
kind: Pod
metadata:
  name: bun-app
  namespace: my-bun-app
spec:
  containers:
  - name: bun-app
    image: bun-app:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: 
    - containerPort: 5000